### ISSUE TITLE
FetchData.py deki İş Yatırım Linkindeki Veri Eksikliği

### ISSUE THREAD

**Issue by ErcanYaman** [urazakgul/isyatirimhisse#10]
Selamlar,

Aşağıdaki linki direkt FetchData.py dosyası içindeki iş yatırım linkinden aldım. Bu sene halka arz olmuş olan ATAKP hissesi için bu linkten gelen en geç data 2-8-2023 tarihine ait ama linkteki başlangıç tarihi aslında 31-12-2022. Dolayısıyla ilk datanın aslında hissenin işlem gördüğü ilk tarih olan 27 Temmuz'a ait olması gerekirdi.

https://www.[isyatirim.com.tr/_layouts/15/Isyatirim.Website/Common/Data.aspx/HisseTekil?hisse=ATAKP&startdate=31-12-2022&enddate=14-08-2023.json](https://www.isyatirim.com.tr/_layouts/15/Isyatirim.Website/Common/Data.aspx/HisseTekil?hisse=ATAKP&startdate=31-12-2022&enddate=14-08-2023.json)

Aşağıdaki ekran görüntüsünde aynı sitedeki şirket kartında 27 Temmuz'da data olduğunu görüyorum. Yukarıdaki linkle şirket kartındaki datanın geldiği source farklı mı bir bilginiz var mıdır?

![image](https://github.com/urazakgul/isyatirimhisse/assets/108731389/bf9a5d6e-b39c-4065-a55b-d5554fa1dd0e)

**Comment by urazakgul** [comment]
Selam, bu da son iki yanıtımla aynı olacak. Testler devam ediyor. Bilgi vereceğim.
