### ISSUE TITLE
Tüm şirketlere ait finansalları tek bir kodla çekip excel dosyasına kaydetme

### ISSUE THREAD

**Issue by GunduzYuruyen** [urazakgul/isyatirimhisse#11]
merhaba, 

bistte yer alan tüm şirketlere ait finansalları tek bir kodla çekip, şirket isimleriyle excel dosyasına kaydetmek istiyorum. Bu konuda yardımcı olabilir misiniz?

Ayrıca data* default olarak dict olarak tanımlanmış; default veri tipini dataframe olarak değiştirebilir misiniz?

*data=fetch_financials(
    symbol=symbols,
    start_year=start_year,
    language=language,
    exchange=exchange
)

**Comment by urazakgul** [comment]
Merhaba, dokümantasyonda örneğini bulabilirsiniz.
