### ISSUE TITLE
syntax hatası

### ISSUE THREAD

**Issue by onurdzd** [urazakgul/isyatirimhisse#12]
Örneklerde verilen ve fonksiyonu çalıştıran await main_wrapper() VSCode run sırasında Syntax error veriyor.

await main_wrapper() aşağıdaki şekilde çağırılırsa sorunsuz çalışmakta

örnek:
from isyatirimhisse import fetch_data, fetch_financials, visualize_data
import asyncio

async def main():
    symbol = 'GARAN'
    start_date = '03-01-2023'

    veriler = await fetch_data(
        symbol=symbol,
        start_date=start_date
    )
    return veriler

async def run():
    sonuc = await main()
    print(sonuc)

async def main_wrapper():
    gorev = asyncio.create_task(run())
    await asyncio.gather(gorev)  

def main_wrapper_asyncio():
    asyncio.run(main_wrapper())  

main_wrapper_asyncio()

**Comment by urazakgul** [comment]
Evet, VS Code'da interactive window'da çalışıyor ama script'te hata veriyor. Çözüm bulabilirsem yazayım.

**Comment by urazakgul** [comment]
Selam,

Aşağıdaki kod Script'te çalışacaktır.

```
from isyatirimhisse import fetch_data
import asyncio
import nest_asyncio
nest_asyncio.apply()

async def main():
    veriler = await fetch_data(symbol='THYAO', start_date='01-01-2023')
    return veriler

async def run():
    sonuc = await main()
    print(sonuc)

async def main_wrapper():
    gorev = asyncio.create_task(run())
    await gorev

asyncio.run(main_wrapper())
```

**Comment by fkucuker** [comment]
veriler = await fetch_data(symbol='THYAO', start_date='01-01-2023') Bu çözümde de maalesef fetch data içine dışardan veri atınca çeşitli sorunlar yaşanıyor.

**Comment by urazakgul** [comment]
Biraz daha açabilir misiniz? Dışarıdan veri örneği, kod, hatalar nelerdir?
