### ISSUE TITLE
ingilizce dil seçeneği - boş satır

### ISSUE THREAD

**Issue by GunduzYuruyen** [urazakgul/isyatirimhisse#13]
merhaba, finansal tablolar > dil seçeneği İngilizce seçilerek indirildiğinde boş satırlar gelmekte. bilginize.

**Comment by urazakgul** [comment]
Merhaba,

Maalesef bunun site kaynaklı olduğunu düşünüyorum. Aşağıdaki URL'e bakalım.

https://www.isyatirim.com.tr/_layouts/15/IsYatirim.Website/Common/Data.aspx/MaliTablo?companyCode=THYAO&exchange=TRY&financialGroup=XI_29&year1=2022&period1=3&year2=2022&period2=6&year3=2022&period3=9&year4=2022&period4=12

Örneğin, 1AEA kodu excel'de boş gelmiş. URL'den bakınca da null olduğunu görebiliriz.
