### ISSUE TITLE
Bilanço detayları hakkında

### ISSUE THREAD

**Issue by Brigade45** [urazakgul/isyatirimhisse#7]
Öncelikle baştan yazayım. Paketin adı isyatirimhisse kabul ediyorum :)
Ama selenium kullanmak biraz problemli.  Proje adını değiştirip selenium'lu kısımları kaldırıp bilanço verilerini buradan alabiliriz.
https://atayi.idealdata.com.tr:3000/cmd=BilancoDetay?symbol=THYAO?konsolide=0?lang=tr
ne dersiniz?

**Comment by urazakgul** [comment]
Evet paketin isminden dolayı yapısını bozar :) ama bir parametre ile kullanıcıya bırakılabilir seçenek.
