### ISSUE TITLE
start_date - end_date arası dışındaki datanın listeye gelmesi

### ISSUE THREAD

**Issue by ErcanYaman** [urazakgul/isyatirimhisse#9]
Selam,

Aşağıdaki kod çalıştırıldığında 31-12-2022 ile 14-08-2023 arasındaki data gelmesi gerekirken 31-12-2022 öncesi ve 14-08-2023 sonrası datanın geldiği görülmektedir.

İnceleyebilir misiniz.?

from isyatirimhisse import fetch_data
from datetime import date

symbol=['ATAKP','KCHOL']

data=(fetch_data(
    symbol=symbol,
    stock_market_index=['XU100'],
    start_date='31-12-' + str((date.today().year-1)),
    end_date=(date.today() - timedelta(days=1)).strftime("%d-%m-%Y"),
    drop_na = False,
    frequency='1d'
).sort_values(by='Date', ascending=True).fillna(0))

print(data)

**Comment by urazakgul** [comment]
Selam, bununla ilgili bir iyileştirme yapmıştım. Sanırım ondan kaynaklanıyor. Kodlarınızı teste dahil ediyorum. Yeni sürümde sorunun ortadan kalkmasını bekliyorum.

**Comment by ErcanYaman** [comment]
Bu sorun devam ediyor. Endeks verileri için start_date - end_date dışındaki günler için de data gelmektedir.

**Comment by ErcanYaman** [comment]
Aşağıdaki script çalıştığında XU100 için 2022 yılının datasının geldiği görülüyor ki hisselerde 2022 için NaN sonuç var. Tarih filtresi endeksler için sağlıklı çalışmıyor gibi.

from isyatirimhisse import fetch_data
from datetime import date, timedelta
import asyncio

async def main():
    symbol = ['KCHOL', 'ASELS']
    stock_market_index = ['XU100']
    start_date = '31-12-' + str((date.today().year - 1))
    end_date = (date.today() - timedelta(days=1)).strftime("%d-%m-%Y")
    frequency = '1d'
    drop_na = False
    language = 'tr'

    veriler = await fetch_data(
        symbol=symbol,
        stock_market_index=stock_market_index,
        start_date=start_date,
        end_date=end_date,
        frequency=frequency,
        drop_na=drop_na,
        language=language
    )

    return veriler

async def run():
    sonuc = await main()
    print(sonuc)

async def main_wrapper():
    gorev = asyncio.create_task(run())
    await gorev

asyncio.run(main_wrapper())

**Comment by urazakgul** [comment]
Sorunu buldum. Küçük bir sürüm çıkaracağım.

**Comment by urazakgul** [comment]
Sürüm çıkarıldı. Geri dönüşlerinizi beklerim.

**Comment by ErcanYaman** [comment]
fixlenmiş teşekkür ederim.
